### PR TITLE
ADD: axios as a dependency

### PR DESCRIPTION
**Pull request by Goku-kun**
I've written some preliminary code and thought about how we should go around in the directory structure but it needs more work. I'll keep pushing on this branch and tag you for reviews.

### CODE REVIEW

**Comment by Goku-kun** [comment]
Also, we won't be needing `@types/dotenv`. Turns out, the library has started supporting it by default. So, I've removed it.

**Comment by Goku-kun** [comment]
Ah, I also noticed that the files you pushed weren't formatted so I've embedded the prettier command in the `npm run compile` command which will format the files every time the code is compiled or the server is started.

**Comment by shashwatrathod** [comment]
> Ah, I also noticed that the files you pushed weren't formatted so I've embedded the prettier command in the `npm run compile` command which will format the files every time the code is compiled or the server is started.

We can add [husky](https://typicode.github.io/husky/#/) to the project.

**Comment by Goku-kun** [comment]
This is actually a good idea. I was thinking about standardizing git commits as well. I haven't worked with husky before although.

**Comment by shashwatrathod** [comment]
> This is actually a good idea. I was thinking about standardizing git commits as well. I haven't worked with husky before although.

I'll add it after your next merge.

**Comment by Goku-kun** [comment]
Oh! I already added it. I think we can close this pull request now. Couple of things going on here actually. I don't want the commit history to look like a spaghetti.

**Comment by shashwatrathod** [comment]
Looks good to me; merging

**Pull request merged**
